package Final;


import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import java.io.IOException;
import java.io.OutputStream;
import javax.swing.JTextArea;
import java.io.PrintStream;


/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Titan
 */
public class Ventana extends javax.swing.JFrame {
    //private final JTextArea textArea;
    private PrintStream standardOut;

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        
        initComponents();
        //textArea = new JTextArea(50, 10);
        //textArea.setEditable(false);
        PrintStream printStream = new PrintStream(new CustomOutputStream1(jTAresultados));
        // keeps reference of standard output stream
        standardOut = System.out;
        // re-assigns standard output stream and error output stream
	System.setOut(printStream);
	System.setErr(printStream);
        
        //add(textArea);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jBsimular = new javax.swing.JButton();
        jTFcantTelefonos = new javax.swing.JTextField();
        jTFcantEnlaces = new javax.swing.JTextField();
        jTFtiempoSimulacion = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTAresultados = new javax.swing.JTextArea();
        jBcerrar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jRBejercicio1 = new javax.swing.JRadioButton();
        jRBejercicio2 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SIMULADOR DE CONMUTADOR TELEFONICO");

        jBsimular.setText("Simular");
        jBsimular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsimularActionPerformed(evt);
            }
        });

        jTFcantTelefonos.setNextFocusableComponent(jTFcantEnlaces);

        jTFcantEnlaces.setNextFocusableComponent(jTFtiempoSimulacion);

        jTFtiempoSimulacion.setNextFocusableComponent(jBsimular);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Cantidad de teléfonos");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Cantidad de enlaces");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Tiempo de simulación");

        jTAresultados.setColumns(20);
        jTAresultados.setEditable(false);
        jTAresultados.setRows(5);
        jScrollPane1.setViewportView(jTAresultados);

        jBcerrar.setText("Cerrar");
        jBcerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcerrarActionPerformed(evt);
            }
        });

        jLabel4.setText("Número entero entre 5 y 100");

        jLabel5.setText("Número entero entre 1 y 10");

        jLabel7.setText("Número entero entre 1 y 36000");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Resultado de la simulación");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tipo de simulación", 0, 0, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        buttonGroup1.add(jRBejercicio1);
        jRBejercicio1.setSelected(true);
        jRBejercicio1.setText("sin cola");
        jRBejercicio1.setToolTipText("Las llamadas no exitosas se descartan");
        jRBejercicio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBejercicio1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRBejercicio2);
        jRBejercicio2.setText("con cola");
        jRBejercicio2.setToolTipText("Las llamadas sin enlace entran en cola FIFO");
        jRBejercicio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBejercicio2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRBejercicio1)
                    .addComponent(jRBejercicio2))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRBejercicio1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRBejercicio2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBsimular)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jBcerrar, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 841, Short.MAX_VALUE)
                        .addComponent(jSeparator1)
                        .addComponent(jLabel6)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                            .addGap(52, 52, 52)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTFcantEnlaces, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTFcantTelefonos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTFtiempoSimulacion, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel7))
                            .addGap(35, 35, 35)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jBsimular))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTFcantTelefonos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFcantEnlaces, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTFtiempoSimulacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(1, 1, 1)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBcerrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBsimularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsimularActionPerformed
        // TODO add your handling code here:
        jTAresultados.setText(""); //para limpiar el textArea
        if(validarCampos()){
            
            int tiempoSimulacion=Integer.parseInt(jTFtiempoSimulacion.getText());
            int cantEnlaces=Integer.parseInt(jTFcantEnlaces.getText());
            int cantTelefonos=Integer.parseInt(jTFcantTelefonos.getText());
            
            if(jRBejercicio1.isSelected()){
                Ejercicio1v1 sim=new Ejercicio1v1(tiempoSimulacion, cantEnlaces, cantTelefonos);
                sim.simular();
                sim.imprimirResultados();
            }
            else{
                Ejercicio2v1 sim=new Ejercicio2v1(tiempoSimulacion, cantEnlaces, cantTelefonos);
                sim.simular();
                sim.imprimirResultados();
            
            }
            
            
        
        }
        
    }//GEN-LAST:event_jBsimularActionPerformed

    private void jBcerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcerrarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jBcerrarActionPerformed

    private void jRBejercicio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBejercicio1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRBejercicio1ActionPerformed

    private void jRBejercicio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBejercicio2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRBejercicio2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBcerrar;
    private javax.swing.JButton jBsimular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRBejercicio1;
    private javax.swing.JRadioButton jRBejercicio2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTAresultados;
    private javax.swing.JTextField jTFcantEnlaces;
    private javax.swing.JTextField jTFcantTelefonos;
    private javax.swing.JTextField jTFtiempoSimulacion;
    // End of variables declaration//GEN-END:variables


protected boolean validarCampos(){
        if (jTFcantTelefonos.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "El campo Cantidad de teléfonos está vacio");
            jTFcantTelefonos.requestFocus();
            return false;
        }
        
        if(!esNumerico(jTFcantTelefonos.getText())){
            JOptionPane.showMessageDialog(this, "El campo Cantidad de teléfonos debe ser numérico");
            jTFcantTelefonos.requestFocus();
            return false;
        }
        
        if(Integer.parseInt(jTFcantTelefonos.getText())<5 || Integer.parseInt(jTFcantTelefonos.getText())>100){
            JOptionPane.showMessageDialog(this, "El campo Cantidad de teléfonos debe estar comprendido entre [5 - 100]");
            jTFcantTelefonos.requestFocus();
            return false;
        }
        
        if (jTFcantEnlaces.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "El campo Cantidad de enlaces está vacio");
            jTFcantEnlaces.requestFocus();
            return false;
        }
        
        if(!esNumerico(jTFcantEnlaces.getText())){
            JOptionPane.showMessageDialog(this, "El campo Cantidad de enlaces debe ser numérico");
            jTFcantEnlaces.requestFocus();
            return false;
        }
        
        if(Integer.parseInt(jTFcantEnlaces.getText())<1 || Integer.parseInt(jTFcantEnlaces.getText())>10){
            JOptionPane.showMessageDialog(this, "El campo Cantidad de Enlaces debe estar comprendido entre [1 - 10]");
            jTFcantEnlaces.requestFocus();
            return false;
        }
        
        if (jTFtiempoSimulacion.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "El campo Tiempo de simulación está vacio");
            jTFtiempoSimulacion.requestFocus();
            return false;
        }
        
        if(!esNumerico(jTFtiempoSimulacion.getText())){
            JOptionPane.showMessageDialog(this, "El campo Tiempo de simulación debe ser numérico");
            jTFtiempoSimulacion.requestFocus();
            return false;
        }
        
        if(Integer.parseInt(jTFtiempoSimulacion.getText())<1 || Integer.parseInt(jTFtiempoSimulacion.getText())>36000){
            JOptionPane.showMessageDialog(this, "El campo Tiempo de simulacion debe estar comprendido entre [1 - 36000]");
            jTFtiempoSimulacion.requestFocus();
            return false;
        }
        
        
        
       
        
        return true;
    }


    public boolean esNumerico(String cadenaAEvaluar){
        boolean b;
        String expresionRegular="[0-9]+";
        return b=Pattern.matches(expresionRegular,cadenaAEvaluar);     
    }
    
    //*********************** INNER CLASS *********************
    
    public class CustomOutputStream1 extends OutputStream {
	private JTextArea textArea;

	public CustomOutputStream1(JTextArea textArea) {
		this.textArea = textArea;
	}

	@Override
	public void write(int b) throws IOException {
		// redirects data to the text area
        textArea.append(String.valueOf((char)b));
        // scrolls the text area to the end of data
        textArea.setCaretPosition(textArea.getDocument().getLength());
	}
    }
    
    //******************** FIN INNER CLASS ************************
    
        

}
